# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_irrigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='CropStage',
            field=models.CharField(max_length=20),
        ),
    ]
