# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190630_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='CropStage',
            field=models.IntegerField(choices=[(1, '1ststage'), (2, '2ndstage'), (3, '3rdstage'), (4, '4thstage'), (5, '5thstage')], default='1ststage'),
        ),
    ]
