# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20190706_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='username1',
            field=models.CharField(max_length=30),
        ),
    ]
